
FROM maven:3.8-openjdk-17 AS build

WORKDIR /app

COPY "SistemaDeAgendamento - FullStack/pom.xml" .


RUN mvn dependency:go-offline


COPY "SistemaDeAgendamento - FullStack/src" ./src


RUN mvn clean package -DskipTests


FROM openjdk:17-slim

WORKDIR /app


COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
